version: '2.1'

orbs:
  cypress: cypress-io/cypress@3

workflows:
  use-my-orb:
    jobs:
      - cypress/run:
          cypress-command: npm run cypress:run --e2e

      store_artifacts:
        executor: cypress-executor
        steps:
          - store_artifacts:
              path: cypress/reports
              destination: test-results

      - run:
          name: Send Email with Test Report
          command: |
            npm install nodemailer
            node send-email.js