version: 2.1

jobs:
  build:
    docker:
      - image: cypress/base:10 # Adjust the Cypress base image version as per your project requirements
    working_directory: ~/repo

    steps:
      - checkout

      # Install Xvfb and other necessary dependencies
      - run:
          name: Install Dependencies
          command: |
            apt-get update
            apt-get install -y xvfb libgtk-3-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2

      # Start Xvfb and set DISPLAY
      - run:
          name: Start Xvfb
          command: |
            Xvfb :99 -screen 0 1920x1080x24 &
            export DISPLAY=:99

      # Install Cypress and run tests
      - run:
          name: Run Cypress Tests
          command: |
            npm install
            npm run cypress:run

      # Store Cypress test results as artifacts
      - store_artifacts:
          path: cypress/reports
          destination: test-results
