version: 2.1

executors:
  cypress-executor:
    docker:
      - image: circleci/node:14.17.0-browsers
        environment:
          DISPLAY: ":99"
    working_directory: ~/repo

jobs:
  build-test-env:
    executor: cypress-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install

  run-cypress-test:
    executor: cypress-executor
    steps:
      - checkout
      - run:
          name: Start Xvfb
          command: Xvfb :99 -screen 0 1920x1080x24
          background: true
      - run:
          name: Verify installed dependencies
          command: npm ls --depth=0
      - run:
          name: Run Cypress tests
          command: npx cypress run --headed
          # For headless mode use: command: npx cypress run --headless

  store-test-artifacts:
    executor: cypress-executor
    steps:
      - checkout
      - store_artifacts:
          path: cypress/screenshots
          destination: screenshots

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-test-env
      - run-cypress-test:
          requires:
            - build-test-env
      - store-test-artifacts:
          requires:
            - run-cypress-test
