version: 2.1

executors:
  cypress-executor:
    docker:
      - image: cypress/base:latest
        environment:
          DISPLAY: ":99"

jobs:
  build-test-env:
    executor: cypress-executor
    steps:
      - checkout

      # Install Cypress
      - run:
          name: Install Cypress
          command: npm install cypress --save-dev

  run-cypress-test:
    executor: cypress-executor
    steps:
      - checkout

      # Run Cypress tests
      - run:
          name: Run Cypress tests
          command: npm run cypress:run

  store-test-artifacts:
    executor: cypress-executor
    steps:
      - checkout

      # Store Cypress test results as artifacts
      - store_artifacts:
          path: cypress/reports
          destination: test-results


workflows:
  version: 2
  build-and-test:
    jobs:
      - build-test-env
      - run-cypress-test:
          requires:
            - build-test-env
            - store-test-artifacts:
                requires:
                  - run-cypress-test
