version: 2.1

executors:
  cypress-executor:
    docker:
      - image: cypress/base:latest
        environment:
          DISPLAY: ":99"

jobs:
  install:
    executor: cypress-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install

  test:
    executor: cypress-executor
    steps:
      - checkout
      - run:
          name: Install Cypress
          command: npm install cypress --save-dev
      - run:
          name: Run Cypress tests
          command: npm run cypress:run
      - store_artifacts:
          path: cypress/reports
          destination: test-results
      - run:
          name: Send Email with Test Report
          command: |
            npm install nodemailer
            node send-email.js

workflows:
  version: 2
  test-and-build:
    jobs:
      - install
      - test:
          requires:
            - install
