version: 2.1

executors:
  cypress-executor:
    docker:
      - image: cypress/base:latest
        environment:
          DISPLAY: ":99"

jobs:
  build-test-env:
    executor: cypress-executor
    steps:
      - checkout
      - run:
          name: Install Cypress
          command: npm ci  # Use 'npm ci' for a clean install based on package-lock.json

  run-cypress-test:
    executor: cypress-executor
    steps:
      - checkout
      - run:
          name: Verify Cypress installation
          command: npx cypress --version
      - run:
          name: Run Cypress tests
          command: npx cypress run

  store-test-artifacts:
    executor: cypress-executor
    steps:
      - checkout
      - store_artifacts:
          path: cypress/reports
          destination: test-results


workflows:
  version: 2
  build-and-test:
    jobs:
      - build-test-env
      - run-cypress-test:
          requires:
            - build-test-env
            - store-test-artifacts:
            
