version: '2.1'

orbs:
  cypress: cypress-io/cypress@3

workflows:
  use-my-orb:
    jobs:
      - cypress/run:
          executor: cypress/base:10
          steps:
            - checkout
            - cypress/run:
                cypress-command: npm run cypress:run --e2e

      - store_artifacts:
          executor: cypress/base:10
          steps:
            - store_artifacts:
                path: cypress/reports
                destination: test-results

      - send-email:
          executor: cypress/base:10
          steps:
            - run:
                name: Install nodemailer
                command: npm install nodemailer
            - run:
                name: Send Email with Test Report
                command: node send-email.js
